services:
  vote:
    build: ./vote
    # use python rather than gunicorn for local deve
    command: python app.py
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl","-f","http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ./vote:/app
    ports:
      - "5005:80"
    networks:
      - front-tier
      - back-tier
  
  redis:
    image: redis:alpine
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/redis.sh
      interval: 5s
    networks:
      - back-tier

networks:
  front-tier:
  back-tier: